language: php

dist: trusty

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1